### ISSUE TITLE
AWS Single Tenant Module: Add ability to configure custom (non-SES) SMTP server in dbt install script

### ISSUE THREAD

**Issue by klehmer** [fishtown-analytics/terraform-aws-dbt-cloud-single-tenant#16]
As a user, I'd like to either generate SES values and have them injected into the dbt config file OR inject my own custom SMTP server values into the config file.

**Comment by natty-li** [comment]
https://github.com/fishtown-analytics/terraform-aws-dbt-cloud-single-tenant/pull/26
